# Generated by Django 3.0.7 on 2020-07-01 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200701_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banks',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
